# Generated by Django 5.0.3 on 2024-05-14 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookingweb', '0002_alter_comment_options_alter_rating_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag_type__name', 'name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='tagtype',
            options={'ordering': ['name'], 'verbose_name': 'Тип тега', 'verbose_name_plural': 'Типы тегов'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя тега'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookingweb.tagtype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='tagtype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя типа'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название подборки')),
                ('description', models.TextField(verbose_name='Описание подборки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор подборки')),
                ('recipes', models.ManyToManyField(to='cookingweb.recipe', verbose_name='Рецепты в подборке')),
            ],
            options={
                'verbose_name': 'Подборка рецептов',
                'verbose_name_plural': 'Подборки рецептов',
            },
        ),
    ]
