# Generated by Django 5.0.3 on 2024-05-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookingweb', '0004_remove_recipe_recipe_rating_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtype',
            name='color',
            field=models.CharField(choices=[('white', 'Белый'), ('red', 'Красный'), ('orange', 'Оранжевый'), ('yellow', 'Желтый'), ('green', 'Зеленый'), ('lightblue', 'Голубой'), ('blue', 'Синий'), ('purple', 'Фиолетовый'), ('pink', 'Розовый'), ('brown', 'Коричневый'), ('gray', 'Серый')], default='white', max_length=10, verbose_name='Цвет тега'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Изображение'),
        ),
    ]
