# Generated by Django 5.0.3 on 2024-05-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookingweb', '0005_tagtype_color_alter_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='content',
            field=models.TextField(default='', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
